services:
  postgres:
    image: postgres:latest
    container_name: observa_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: observa-main
    ports:
      - '5432:5432'
    volumes:
      - observa_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: observa_streams
    ports:
      - '6379:6379'
    volumes:
      - observa_streams_data:/data

volumes:
  observa_data:
  observa_streams_data:
